server:
  port: 8080
zuul:
  routes:
    account:
      path: /accountservice/**
      serviceId: AccountService
    user:
      path: /userservice/**
      serviceId: UserService

ribbon:
  eureka:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/